services:
  - type: web
    name: phishguard-backend
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/phishguard-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 21
